# Configuration file for auto_calc_contrast_in_ocean python code

input:
  format       : envi
  infiles      : 'Input/*Itot.dB.grd' #input file glob

  incangsuffix : .inc
  indeg        : False

  uselandmask   : True
  maskfile      : landmask     # One mask file each basename.  0 = water, 1 = land/notwater

process: # Clean sea pixel ID processing options
  incangbinsize : 2            # For incidence angle binning to get clean sea pixels from the PDF of the values in infiles
  setinclolim   : True
  setinchilim   : True
  inclolim      : 40
  inchilim      : 58
  bootstrap     : True         # Use solution from last angle bin for current bin

  # For each infile line/flight/DT, calculate contrasts for the following
  # files (contrast = Value at same incang in clean sea / Value)
  filetype :
    - 'VVVV*.grd'
    - 'HHHH*.grd'
    - 'HVHV*.grd'
  exclude :
    - 'dB'

output:
  format  : envi
  outdir  : Output
