# Configuration file for auto_calc_contrast_in_ocean python code

input:
  format     : geotiff
  infiles    : '1_subset_*_EC.tif' #input file glob or filename

  indeg      : True
  indb       : False

  uselandmask   : True
  maskfile      : landmask_20220623 # One mask file each basename.  0 = water, 1 = land/notwater

process: # Clean sea pixel ID processing options
  incangbinsize : 1            # [deg] For incidence angle binning to get clean
                               # sea pixels from the PDF of the values in
                               # infiles
  setinclolim   : False
  setinchilim   : False
  inclolim      : 30           # [deg]
  inchilim      : 58           # [deg]
  bootstrap     : False        # Use solution from last angle bin for current bin

  polarization  : VV

output:
  format  : geotiff
  outdir  : f'pyDR_{infile}'
